### ISSUE TITLE
Addition of coefficient modification to c interface 

### ISSUE THREAD

**Issue by ndinsmore** [coin-or/Clp#102]
For Clp.jl it would be great to have the ability to modify matrix coefficents through the C interface.

This was discussed in:  https://github.com/JuliaOpt/Clp.jl/pull/56

@mlubin put forth the recomendation of :
```c
void Clp_modifyCoefficient(Clp_Simplex *model, int row, int column, double newElement,
  bool keepZero)
{
  model->model_->modifyCoefficient(row, column, newElement, keepZero);
}
```

It would also potentially be useful to have the ability to modify the coeffients using a sparse matrix to specify with coeffiecents to add or replace.

**Comment by svigerske** [comment]
If you can provide code to modify a set of coefficients, then we can add this, too.

**Comment by svigerske** [comment]
Note that `keepZero` will changed to an int with Clp 1.18, see #124.
