### ISSUE TITLE
Wrong objective value in MIPLIB 2017 instance

### ISSUE THREAD

**Issue by h-g-s** [coin-or/Clp#103]
For problem [irish-electricity](http://miplib2017.zib.de/instance_details_irish-electricity.html)  , which is included in the MIPLIB 2017 benchmark set the optimal LP relaxation objective is  **2.5462545620e+06**, checked with Gurobi and CPLEX. GLPK also finds this solution with some effort.

CLP computes a wrong objective value of  **2454773.283** .  It takes about five minutes with dualS.   This objective value appears with very different parameter settings. Since this objective value is not very different from the correct objective value, I suspected that it was something related to the presolve forgetting about some fixed variable, but without presolve the same result is produced. Could you please check it @jjhforrest  ?

Some interesting characteristics of this instance: 
- it has many continuous variables and some binary variables
- the objective function contains only unitary coefficients

**Comment by jjhforrest** [comment]
A tolerance issue.  I can get continuous (i.e. without any integer preprocessing) of 2456635.2 with largest infeasibility of 1.4e-8

**Comment by h-g-s** [comment]
If I understood correctly, CLP finds a better solution than the other solvers, even considering strict tolerances, is it ?

**Comment by jjhforrest** [comment]
Haroldo,It may be that they are taking into account some integer stuffJohn


-------- Original Message --------
Subject: Re: [coin-or/Clp] Wrong objective value in MIPLIB 2017 instance
(#103)

**Comment by h-g-s** [comment]
Good that this is not a bug, closing
