### ISSUE TITLE
'CLP_VERSION' was not declared in this scope

### ISSUE THREAD

**Issue by gaolong** [coin-or/Clp#104]
Dear Clp developer,

I was trying to build Clp under linux environment but I got this following errors. Thank you!

Best,
Long

command:  ./coinbrew build --main-proj=Clp --test

/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp: In function 'const char* Clp_Version( ':
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp:198:10: error: 'CLP_VERSION' was not declared in this scope
   return CLP_VERSION;
          ^~~~~~~~~~~
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp: In function 'int Clp_VersionMajor()':
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp:203:10: error: 'CLP_VERSION_MAJOR' was not declared in this scope
   return CLP_VERSION_MAJOR;
          ^~~~~~~~~~~~~~~~~
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp: In function 'int Clp_VersionMinor()':
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp:207:10: error: 'CLP_VERSION_MINOR' was not declared in this scope
   return CLP_VERSION_MINOR;
          ^~~~~~~~~~~~~~~~~
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp: In function 'int Clp_VersionRelease()':
/home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp:211:10: error: 'CLP_VERSION_RELEASE' was not declared in this scope
   return CLP_VERSION_RELEASE;
          ^~~~~~~~~~~~~~~~~~~
In file included from /home/gaolong/Software/Clp/Clp/Clp/src/Clp_C_Interface.cpp:11:0:
/home/gaolong/Software/Clp/CoinUtils/CoinUtils/src/CoinHelperFunctions.hpp: In instantiation of 'void CoinMemcpyN(const T*, CoinByteArray, T*) [with T = char; CoinByteArray = long int]':
/home/gaolong/Software/Clp/CoinUtils/CoinUtils/src/CoinHelperFunctions.hpp:619:31:   required from here
/home/gaolong/Software/Clp/CoinUtils/CoinUtils/src/CoinHelperFunctions.hpp:331:30: warning: conversion to 'CoinBigIndex {aka int}' from 'long int' may alter its value [-Wconversion]
   for (CoinBigIndex n = size / 8; n > 0; --n, from += 8, to += 8) {
                         ~~~~~^~~
make[2]: *** [Clp_C_Interface.lo] Error 1
make[2]: Leaving directory `/home/gaolong/Software/Clp/build/Clp/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/gaolong/Software/Clp/build/Clp/src'
make: *** [all-recursive] Error 1
[gaolong@node062 Clp]$ make install
make: *** No rule to make target `install'.  Stop.

**Comment by tkralphs** [comment]
I just built on Linux from a fresh checkout with
```
./coinbrew fetch build Clp --test
```
and had no problems. Can you build from a clean checkout and make sure? I didn't see the fetch command specified. 

That symbol that's missing should be defined in the automatically generated header file `build/Clp/src/config_clp.h`. Can you check to see whether that file exists and does in fact define those symbols. Then we'll go from there.

**Comment by svigerske** [comment]
Closing as not reproducible. `Clp_C_Interface.cpp` has an `#include "ClpConfig.h"` at the top, which should take care of including `config_clp.h`, which defines `CLP_VERSION`, etc.
