### ISSUE TITLE
immintrin.h library replacement for ARM (Raspbian and GCC)

### ISSUE THREAD

**Issue by msalgadob** [coin-or/Clp#106]
Hello. 

Compiling Clp on Raspbian Stretch presents some problems with gcc compiler due to immintrin.h library (compatible with i386 structures) in files:

ClpSimplexDual.cpp: line 3560
ClpPackedMatrix.cpp: line 6753

I replaced immintrin.h library with arm_neon.h according to ARM processors and it compiles perfect. Please consider these changes for ARM compatibility.

**Comment by svigerske** [comment]
Please check whether the committed fix does this for you? I'm not sure that `__arm__` is the right define to look for.
