### ISSUE TITLE
Register keyword

### ISSUE THREAD

**Issue by wo3kie** [coin-or/Clp#107]
Hi,

We are using and really appreciate your library, however, could you consider removing `register` keyword from variable declarations? Otherwise, we have to make some weird hacks to use your library with a new clang++ compiler.

https://en.cppreference.com/w/cpp/keyword/register

Thank you,
Łukasz Czerwiński
Beit.Inc Company

**Comment by tkralphs** [comment]
This is certainly worth considering, but could you provide more details about what problems you're having? Clp is built regularly with clang and hasn't had any problems.

https://travis-ci.org/coin-or/Clp/builds

Pull requests are always welcome!

**Comment by wo3kie** [comment]
Hi,

Thank you for your response. It has been removed in clang++ 3.8.

https://www.bfilipek.com/2017/01/cpp17features.html?m=1#remove-deprecated-use-of-the-register-keyword

Łukasz

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by svigerske** [comment]
In Clp, I only see `register` used in CoinAbcCommon.hpp, which I think is not used unless you enable Aboca. Is this the one you mean, or you mean CoinUtils?

**Comment by wo3kie** [comment]
Yes, exactly, this is the file I am talking about. We are using 'bazel' and looks like it builds the whole library with all files even though we are using only a subset of it. We will prepare a Pull Request later on today.

Regards,
Pozdrawiam,
Łukasz


________________________________________
Od: Stefan Vigerske <notifications@github.com>
Wysłane: sobota, 18 maja 2019 16:55
Do: coin-or/Clp
DW: Łukasz Czerwiński; Author
Temat: Re: [coin-or/Clp] Register keyword (#107)

In Clp, I only see register used in CoinAbcCommon.hpp, which I think is not used unless you enable Aboca. Is this the one you mean, or you mean CoinUtils?

**Comment by svigerske** [comment]
@jjhforrest took this out in https://projects.coin-or.org/Clp/changeset/2471/

@tkralphs can you check why the mirroring to GitHub seems to be broken?
