### ISSUE TITLE
SEGV_MAPERR in libOsiClp.so.1 when use JNI

### ISSUE THREAD

**Issue by tongcx** [coin-or/Clp#112]
Maybe this issue is more relevant here. Wonder whether it's due to run out of memory or sth. Also is there a way to find out which line in C++ failed? I only have assembly.

https://github.com/google/or-tools/issues/1509

**Comment by tongcx** [comment]
Updated the ticket, found that in `int userFactorizationFrequency = modelPtr_->factorization()->maximumPivots();` somehow `factorization()` is null

**Comment by tkralphs** [comment]
This is very strange. If there's a way you could make it possible to replicate this in stand-alone Clp, that would be helpful. Does the or-tools hand an instance file to a stand-alone binary of Clp? If so, you could get that file and see if the problem occurs when running Clp directly. Otherwise, it will be tough for us to debug it.

**Comment by tongcx** [comment]
seems stack is
```
OsiClpSolverInterface::initialSolve
CbcSolver::initialSolve
CbcModel::initialSolve
```

**Comment by tongcx** [comment]
Got the full stack trace
```
Thread 749 "java" hit Breakpoint 1, OsiClpSolverInterface::initialSolve (this=0x7f24b001c580) at OsiClpSolverInterface.cpp:80
warning: Source file is more recent than executable.
80	  int userFactorizationFrequency = modelPtr_->factorization()->maximumPivots();
#0  OsiClpSolverInterface::initialSolve (this=0x7f24b001c580) at OsiClpSolverInterface.cpp:80
#1  0x00007f246656f815 in CbcModel::initialSolve (this=this@entry=0x7f12ebe0f470) at CbcModel.cpp:5460
#2  0x00007f246687ffa7 in CbcMain1 (argc=argc@entry=3, argv=argv@entry=0x7f24b0045d20, model=..., callBack=callBack@entry=0x7f2466871c60 <dummyCallBack(CbcModel*, int)>, parameterData=...) at CbcSolver.cpp:3745
#3  0x00007f24668abeb0 in callCbc1 (input2=input2@entry=0x7f2464ddc802 "-solve ", model=..., callBack=callBack@entry=0x7f2466871c60 <dummyCallBack(CbcModel*, int)>, parameterData=...) at CbcSolver.cpp:1152
#4  0x00007f24668ac0ae in callCbc (input2=0x7f2464ddc802 "-solve ", babSolver=...) at CbcSolver.cpp:1053
#5  0x00007f2464afa6bb in operations_research::CBCInterface::Solve(operations_research::MPSolverParameters const&) () from /mnt/mesos/sandbox/sandbox/tmp/ortools/libortools.so
#6  0x00007f2464b08b25 in operations_research::MPSolver::Solve(operations_research::MPSolverParameters const&) () from /mnt/mesos/sandbox/sandbox/tmp/ortools/libortools.so
#7  0x00007f2464b08c6c in operations_research::MPSolver::Solve() () from /mnt/mesos/sandbox/sandbox/tmp/ortools/libortools.so
#8  0x00007f246798975e in Java_com_google_ortools_linearsolver_main_1research_1linear_1solverJNI_MPSolver_1solve_1_1SWIG_10 () from /mnt/mesos/sandbox/sandbox/tmp/ortools/libjniortools.so
```
Seems it's failing on the first initialSolve. Right now I'm trying to see why factorization is null. Would be great if you can point me to where factorization should be set.

**Comment by tongcx** [comment]
Root caused the problem, classic Java being Java. When Java load native libraries, it doesn't detect symbol conflict, instead the first loaded win silently. Turns out we depends on another package that load a different version of CLP, which shadow the CLP used in CBC. When CBC calls the incompatible version of CLP, it will crash since factorization isn't initialized in that version of ClpSimplex.
