### ISSUE TITLE
undefined symbol: _ZTI18CoinMessageHandler

### ISSUE THREAD

**Issue by martynassateika** [coin-or/Clp#115]
Currently getting this error when using Clp on Linux.

The program that uses it tries to load just Clp, and not CoinUtils, yet it looks like this symbol is part of CoinUtils.

I went through the compilation instructions in the Clp website and can see both .so files in the lib directory.

Is it somehow possible to make it output a single shared library containing both libclp and libcoinutils in one file?

I am using Clp version 1.15.11.

**Comment by tkralphs** [comment]
CoinUtils is one of the libraries used by Clp, so there is no way to "load just Clp." This error would most likely indicate the mixing of incompatible versions. Did you build from source? Or install a package? Or maybe both? That could be the problem. In general, you should not have any problems with a fresh install, provided there are no old versions lurking around. 

In any case, you are using a very old version of Clp, so the first step would be to remove everything currently installed and get the latest release. If you are building from source with [coinbrew](https://github/com/coin-or/coinbrew), you can add
```
--enable-static --disable-shared
```
if you want to include the CoinUtils library into the binary, but there is probably not much advantage to doing this. Almost all packages in Linux use shared libraries.

**Comment by svigerske** [comment]
Closing as no response from reporter.
