### ISSUE TITLE
CInterface: maximumIterations does not follow naming convention

### ISSUE THREAD

**Issue by mtanneau** [coin-or/Clp#119]
Functions in the C interface follow the naming convention `Clp_<function name>` but `maximumIterations` (see [header](https://github.com/coin-or/Clp/blob/85f522ee1e208d5b7332c1e40c3af56774a49d20/Clp/src/Clp_C_Interface.h#L183) and [.cpp](https://github.com/coin-or/Clp/blob/85f522ee1e208d5b7332c1e40c3af56774a49d20/Clp/src/Clp_C_Interface.cpp#L497)) does not.

**Comment by svigerske** [comment]
They seem to have been renamed to fit to others on master in the meanwhile.
