### ISSUE TITLE
C Interface: Unknown type name 'bool'

### ISSUE THREAD

**Issue by lorenzleutgeb** [coin-or/Clp#124]
You are using `bool` here, without including `stdbool.h`. I can't compile anything with this header. My fix was to add
```c
#include <stdbool.h>
```
in the preamble.

https://github.com/coin-or/Clp/blob/b06994a3bb7f5fe8f651f7047b914ab150f0472f/Clp/src/Clp_C_Interface.h#L148

**Comment by tkralphs** [comment]
@svigerske Looks like you added this particular line.

**Comment by svigerske** [comment]
Ooh, thanks. I totally forgot that.
It's probably easiest to just change this to an int instead of requiring C99 just for that.
