### ISSUE TITLE
solutions outside bounds

### ISSUE THREAD

**Issue by jonreiter** [coin-or/Clp#125]
i am getting back solutions described as optimal where, for a variable bounded below by 0, the value is more than the tolerance below 0.

i get the same solution of -1.38e-5 for one variable regardless of whether the tolerance is 1e-5, 1e-6...1e-9, etc.  to be clear the same variable is showing the same optimal value independent of the tolerance -- and it is more than the tolerance below it's lower bound in every case.

is this expected?  how closely are the tolerances supposed to be followed?  or does this just mean my tolerance is set too low?  i thought 1e-5 was pretty mild but could be wrong.

i have an example problem with 1125 variables and 6249 constraints which reliably reproduces the issue.  i can post that (somehow) if needed.

**Comment by jjhforrest** [comment]
Should not happen.  Is your problem badly scaled?

My guess is that while the primary problem status says optimal the 
secondary status says -

  2 - scaled problem optimal - unscaled problem has primal  infeasibilities

If you are using standalone executable, you could try

clp xxxxx.mps -duals -scaling off -duals

If you send problem to me I will see what can be done.

**Comment by jonreiter** [comment]
that is indeed the secondary status and if i disable scaling the problem
also goes away.

i can email you the problem if you'd like.  if it's just a poorly scaled
setup i can live with that too.

**Comment by tkralphs** [comment]
I'm going to close this issue, since it doesn't seem to be a bug. Feel free to re-open.
