### ISSUE TITLE
Message "using xxx columns not 3000"

### ISSUE THREAD

**Issue by zhu-he** [coin-or/Clp#128]
I'm using clp 1.17.3, and my program output some strange messages "using xxx columns not 3000", even if the logging is turned off. It is related to the following codes
https://github.com/coin-or/Clp/blob/de9bae9dcdcbc1b7c759f1aeb0ce360a58639b75/Clp/src/ClpSolve.cpp#L3039-L3040
What does it mean, and how do I turn off the output?

**Comment by svigerske** [comment]
https://github.com/coin-or/Clp/commit/5443b4c9aff4416efb2cce2abe761a37e9ca9f22#diff-8f9d2ed4680dd828e0c7c5d667d77b01 seems to have added a number of printf's. Is this just debug-output, @jjhforrest ?

**Comment by jjhforrest** [comment]
Sorry about that - lines 3039/40 of ClpSolve.cpp were part of a work in 
progress.

**Comment by svigerske** [comment]
printf taken out by 4a00fbbc4b
