### ISSUE TITLE
Missing seed option in C api

### ISSUE THREAD

**Issue by snurkabill** [coin-or/Clp#133]
Hi, 

I am using java-clp library (https://github.com/quantego/clp-java), which is built on top of C API of Clp. The problem is, that C API does not provide a function to set random seed. 

Time to time I am having a problem with reproducibility of my experiments and I found out that it is due to Clp optimization, so I guess that since the seed is set nowhere, zero value is used(?) which, in this case, represents TimeOfDay() value and hence my results sometimes vary. 

Do you have any ideas or hints, what could I do? Or would it be possible to provide seed setter to C API? 

Thanks!

**Comment by tkralphs** [comment]
I guess it should be easy to add this to the C API pretty easily. If you submit a PR, that will definitely move things along, though :).

**Comment by snurkabill** [comment]
What about the PR?
