### ISSUE TITLE
Dependency on libgfortran.so.3

### ISSUE THREAD

**Issue by GeorchW** [coin-or/Clp#146]
The CLP binary (`/bin/clp`) on Linux seems to have a dependency on `libgfortran.so.3`. Is there a possibility to run CLP without it? My package manager does not have such old versions of the fortran library, and building it from source takes days and is tedious.

**Comment by tkralphs** [comment]
What binary are you trying to use? The Linux binaries we currently provide have some issues with dependencies like you have observed. This is something we would like to address, but for now, there will be these incompatibilities. If you are on Debian/Ubuntu or Fedora, you should be able to install Clp from your package manager. Otherwise, it's easy to build from source on Linux, should just take a few minutes and then you would not have an issue.

**Comment by GeorchW** [comment]
Yes, I was referring to the Linux binaries. I am on Arch Linux :-) .

Building from source does not work, either: Using `coinbrew` on the latest version, as described in the README, I'm getting errors while building `ThirdParty/Mumps`. They look like this: 
```
/path/to/coinbrew/ThirdParty/Mumps/MUMPS/src/dmumps_comm_buffer.F:2667:23:

 2658 |         CALL MPI_PACK( WHAT, 1, MPI_INTEGER,
      |                       2
......
 2667 |         CALL MPI_PACK( LIST_SLAVES, NSLAVES, MPI_INTEGER,
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
```
Is there a specific version I should try instead?

**Comment by svigerske** [comment]
Mumps source (both 4.10.0 and 5.3.1) doesn't compile with the GCC 10 out-of-the-box anymore. You can use `ADD_FCFLAGS=-std=legacy` to work around this.
Or skip ThirdParty-Mumps for your build of Clp.

**Comment by GeorchW** [comment]
How do I do this via Coinbrew?

**Comment by tkralphs** [comment]
Depending on which option you want to try and which Clp version you want, you can either do, e.g.,
```
coinbrew build Clp@releases/1.17.6 ADD_FCFLAGS=-std=legacy
```
or
```
coinbrew build Clp@releases/1.17.6 --skip=ThirdParty/Mumps
```
or even just
```
coinbrew build Clp@releases/1.17.6 --no-third-party
```

**Comment by GeorchW** [comment]
That results in 
```
coinbrew/Clp/Clp/src/ClpCholeskyMumps.cpp:15:10: fatal error: dmumps_c.h: No such file or directory
   15 | #include "dmumps_c.h"
      |          ^~~~~~~~~~~~
compilation terminated.
``` 

:-/

**Edit:** To be clear, the above output is the result of the last line (`--no-third-party`).
**Edit2:** To be *more* clear, the same output also comes - as expected - with `--skip=ThirdParty/Mumps`. The first line tries to download a repository with the name `ADD_FCFLAGS=-std=legacy`. Using `ADD_FCFLAGS=-std=legacy` as an env variable has no effect.

**Comment by tkralphs** [comment]
Sorry, I've been actively working on coinbrew and just fixed a bug I introduced that was causing at least some of the issues you are seeing. You may also need to wipe your build directory. Can you try pulling the latest changes to coinbrew and deleting the `build/` directory? I just tried 
```
coinbrew build Clp@releases/1.17.6 --no-third-party
```
and it built with no errors.

**Comment by tkralphs** [comment]
I fixed a number of bugs related to the recent reorganization of the code this morning so sorry if you happen to have gotten caught with any of the buggy versions. Things seem to have settled out now. 

Also, in case it's useful, I did want to point out that there are builds with a very old version of Ubuntu (the ones named *precise*) that are bundled with all the dependent libraries so that Cbc should run out of the box on any recent Linux, as well as static builds (*static*) that include statically linked executables. You probably link to these from another code, though.

Oh, and there are also these newly released binaries from Julia Build: https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases

**Comment by GeorchW** [comment]
The Julia releases give an exec format error (at least `bin/clp`; I've tried two of the provided versions). I can't see builds on bintray or travis that are built for precise, and the Ubuntu package search does not allow for searching for packages of precise since 2017. The old releases are not searchable.

But at least the coinbrew build worked, such that I do now have a working binary. 

One more question: The binary crashes when given an LP file, without notice on what the problem might be. Is this an indicator for a broken binary, or is CLP just not able to parse LP files? (I know that LP files are not standardized, but this one works with both Gurobi and Mosek.)

**Edit:** Nvm, mps seems to work. Thanks a lot!

**Comment by h-g-s** [comment]
Could you provide the LP file  ?

**Comment by tkralphs** [comment]
Clp does read LP files in general, so yes, please post the file that is having an issue (or upload it somewhere and provide a link if it is very large).

**Comment by GeorchW** [comment]
I'm afraid I can't due to NDAs :-/ - but I can try narrowing down the problem

**Comment by GeorchW** [comment]
Hmm, I've briefly tried to narrow down the problem, but the core issue is that the parser only throws a CoinError when encountering a problem, without stating a line or even a message along with it. I'd have to write a script to bisect the problem to be able to narrow it down, since I would have to retain at least some of the semantics of the LP file.

It does, however, contain dots in variable names, if that is an issue.

**Comment by tkralphs** [comment]
I guess dots in variables names could very well be an issue. Why don't you open a separate issue for that and we can try to sort it out.

**Comment by GeorchW** [comment]
The point is, if I shorten the LP to just one constraint, one variable bound and one line of the objective, it just works out. I've opened an issue that more generally... well, makes such issues more approachable :-)
