### ISSUE TITLE
fatal error: 'coin/ClpSimplex.hpp' file not found

### ISSUE THREAD

**Issue by smithla02** [coin-or/Clp#155]
Hello, I am trying to use the golang library [clp](https://github.com/lanl/clp) which provides golang bindings for CLP.

I am trying to test it on linux.

I downloaded the latest distribution of [clp](https://github.com/coin-or/Clp) using [coinbrew](https://coin-or.github.io/coinbrew/) and the following script:
```bash
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew fetch Clp@master
./coinbrew build Clp
```

While trying to use the libary, I have run into the following issue with the import in [clp-interface.cxx](https://github.com/lanl/clp/blob/master/clp-interface.cxx):
``` bash
clp-interface.cxx:1:31: fatal error: coin/ClpSimplex.hpp: No such file or directory
 #include <coin/ClpSimplex.hpp>
```

## Debugging 
The README says the library has only been tested in linux. To try to find the location of the clp library: 
``` bash
pkg-config --libs clp
-L/home/luissmith/dist/lib -lClp
```

If I try to find the `ClpSimplex.hpp` file on the machine, these are the results:
``` bash
find ~/ -type f -name ClpSimplex.hpp
/home/luissmith/Clp/src/ClpSimplex.hpp
/home/luissmith/dist/include/coin-or/ClpSimplex.hpp
```

Is the issue related to the path in one of the newer distributions of CLP? I am realizing the path here is `.../coin-or/ClpSimplex.hpp`, whereas in the [clp-interface.cxx](https://github.com/lanl/clp/blob/master/clp-interface.cxx) it is trying to include `coin/ClpSimplex.hpp`?

I also exported the package path:
```bash
export LD_LIBRARY_PATH="/home/luissmith/dist/lib/"
export PKG_CONFIG_PATH="/home/luissmith/dist/lib/pkgconfig/"
```

If i type the command ```clp``` in command line, the response is:
```bash
Coin LP version devel, build Jul 26 2020
Clp takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
```

## Feedback
I would really appreciate any tips you have on debugging what might be going wrong. And please let me know if you need any more information from me. Thanks.

**Comment by tkralphs** [comment]
Thanks for the detailed report. In the development version of Clp (`master` branch), the directory where header files are installed has been changed from `coin` to `coin-or` as part of a complete re-vamping of our build harness. You can either 
- install the [latest release](https://github.com/coin-or/Clp/releases/tag/releases%2F1.17.6) by either adding the argument `--latest-release` to `coinbrew` or by fetching `Clp@1.17.6` (`Clp@1.17` would also work and would get you the latest version of the stable branch, including any unreleased bug fixes).  
- change the include to `#include <coin-or/ClpSimplex.hpp>

I guess there is a chance the latter won't work if there are breaking changes in the interface, but I don't believe there should be.

**Comment by smithla02** [comment]
Thanks for the advice.

I tried to download the 1.17.6 release:
```bash
./coinbrew fetch Clp@1.17.6
./coinbrew build Clp@1.17.6
```

I then export the pkg config:
```bash
export PKG_CONFIG_PATH="/home/luissmith/dist/lib/pkgconfig/"
```

When I try to find the clp pkg its here:
```bash
pkg-config --libs clp
-L/home/luissmith/dist/lib -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. -L/home/luissmith/dist/lib -lClpSolver -lClp -lcoinasl -lm -ldl -lcoinmumps -lblas -lgfortran -lm -lquadmath -lcoinmetis -lCoinUtils -lz -llapack -lblas -lm -lcoinglpk -ldl -lm
```

However, I am still running into into the error in [clp-interface.cxx](https://github.com/lanl/clp/blob/master/clp-interface.cxx):
``` bash
clp-interface.cxx:1:31: fatal error: coin/ClpSimplex.hpp: No such file or directory
 #include <coin/ClpSimplex.hpp>
```

I do see the file in this location `/home/luissmith/dist/include/coin/ClpSimplex.hpp`:
```bash
find ~/ -type f -name ClpSimplex.hpp
/home/luissmith/Clp/Clp/src/ClpSimplex.hpp
/home/luissmith/dist/include/coin/ClpSimplex.hpp
````

I tried to delete the old `clp` directories manually, because I had trouble doing it via the `coinbrew uninstall` command [which prompted me to fetch / build a project rather than uninstall?]
```bash
./coinbrew uninstall
Welcome to the COIN-OR fetch and build utility

For help, run script with --help.
Please report issues at https://github.com/coin-or/coinbrew
Detailed build documentation at https://coin-or.github.io

Package will be built in /Users/luissmith/build

Please choose a main project to fetch/build by typing 1-18
or simply type the repository name of another project not
listed here.
1. Osi
2. Clp
....
````

Do you have any other ideas what might be the issue?

**Comment by svigerske** [comment]
I think the idea is that you also do a `coinbrew install` first and then use Clp from the installed location.

**Comment by smithla02** [comment]
@svigerske I thought based on the documentation for [coinbrew](https://coin-or.github.io/coinbrew/), that doing a `build` automatically does an `install`.

From the docs:
```
  install: Install all projects in location specified by prefix. This is done
           done automatically after build, so probably not useful in general.
```

So when I do this, I thought it already does an install?
```bash
./coinbrew fetch Clp@1.17.6
./coinbrew build Clp@1.17.6
```

I export the following variables after the `coinbrew build Clp@1.17.6`:
```bash
export PATH=$PATH:/home/<USERNAME>/dist/bin
export PKG_CONFIG_PATH=/home/<USERNAME>/dist/lib/pkgconfig
export LD_LIBRARY_PATH=/home/<USERNAME>/dist/lib
```

Is there anything else I should do so the the golang library [clp](https://github.com/lanl/clp) and [clp-interface.cxx](https://github.com/lanl/clp/blob/master/clp-interface.cxx) can find the right files?

**Comment by svigerske** [comment]
Ah ok, I forget these things.

Maybe it is just clp-interface.cxx that is wrong then. If you now have `/home/<USERNAME>/dist/include/coin/CoinSimplex.hpp`, and clp.pc points to `/home/<USERNAME>/dist/include/coin/` for the incdir, then maybe the one that compiles clp-interface.cxx tries to include `/home/<USERNAME>/dist/include/coin/coin/CoinSimplex.hpp` ?
Having some verbose output when compiling the golang library may help to see where it tries to find the header files.

**Comment by smithla02** [comment]
@svigerske and @tkralphs thank you so much for your suggestions!

> Maybe it is just clp-interface.cxx that is wrong then. If you now have /home/<USERNAME>/dist/include/coin/CoinSimplex.hpp, and clp.pc points to /home/<USERNAME>/dist/include/coin/ for the incdir, then maybe the one that compiles clp-interface.cxx tries to include /home/<USERNAME>/dist/include/coin/coin/CoinSimplex.hpp ?

You were right, it was trying to look for the wrong path.

I copied the source code from the golang library [clp](https://github.com/lanl/clp) and changed the import from
```#include <coin/ClpSimplex.hpp>```
to
```#include <ClpSimplex.hpp>```

This helped to resolve the issue.

**Comment by tkralphs** [comment]
To be clear, there are two issues here. One is the change from `coin` to `coin-or`, but the other is that the `.pc` file gives the full path to the header file directory, so when using `pkg-config`, the proper include is 
```
#include <ClpSimplex.hpp>
```
as you deduced. This also has the advantage of making the include directive agnostic to the change we made. 

For the uninstall, you do need to specify what package to uninstall, since coinbrew is a general package manager and you may have multiple packages built and installed simultaneously, as well as multiple versions of any one package. But in general, just deleting the `dist` directory for a local install is good enough. If you want to start from scratch with a new b uild, you can also delete the `build` directory.

**Comment by smithla02** [comment]
Noted on all points. 

Thanks again for the detailed response!
