### ISSUE TITLE
Idiot not working on Windows

### ISSUE THREAD

**Issue by BjornPetersen** [coin-or/Clp#163]
Using the stand alone CLP executable on Linux it takes 6 seconds to solve the attached instance.
When using libClp on Windows it takes 10 minutes (100 times slower).
It appears that Idiot::crash is finding a "wrong" initials solution that slows down what happens afterward.

Using Visual Studio 2019 and static linking with libClp, libCoinUtils, libOsi, and libOsiClp:
```
#include "OsiClp/OsiClpSolverInterface.hpp"
int main() {
	auto clpSolver = OsiClpSolverInterface();
	clpSolver.readLp("Clp-Dual_50.lp");
	clpSolver.initialSolve();
}
```
[Clp-Dual_50.zip](https://github.com/coin-or/Clp/files/5428070/Clp-Dual_50.zip)
[output.txt](https://github.com/coin-or/Clp/files/5428165/output.txt)

**Comment by jjhforrest** [comment]
Bjorn,

With OsiClpSolverInterface::initialSolve the code decides to do a very 
lightweight Idiot crash - which gets nowhere.  You need a bit more 
tuning.  The following works for me.

#include "ClpSimplex.hpp"
#include "OsiClpSolverInterface.hpp"

int main(int argc, const char *argv[])
{
   OsiClpSolverInterface clpSolver;
   clpSolver.readLp("/tmp/Clp-Dual_50.lp");
   ClpSolve solveOptions;
   solveOptions.setSolveType(ClpSolve::usePrimalorSprint);
   solveOptions.setSpecialOption(1,2,100);
   clpSolver.setSolveOptions(solveOptions);
   clpSolver.initialSolve();
   return 0;
}

John Forrest

**Comment by BjornPetersen** [comment]
Hi John

Thanks, that did the trick.
Is there a guide somewhere for setting these secret parameters/options?

Best regards
Bjørn

**Comment by jjhforrest** [comment]
Bjorn,

There are some hints in ClpSolve.hpp

John Forrest
