### ISSUE TITLE
Compile error due to wrong format string

### ISSUE THREAD

**Issue by christoph-cullmann** [coin-or/Clp#172]
Hi,

The code inside ClpPackedMatrix.cpp (this sequence is there twice)

```
          if(sizeof(CoinBigIndex) == sizeof(int))
            printf("Out of range %d %d %d %g\n", iColumn, j, row[j], elementByColumn[j]);
          else if(sizeof(CoinBigIndex) == sizeof(long))
            printf("Out of range %d %ld %d %g\n", iColumn, j, row[j], elementByColumn[j]);
          else if(sizeof(CoinBigIndex) == sizeof(long long))
            printf("Out of range %d %lld %d %g\n", iColumn, j, row[j], elementByColumn[j]);
```

leads to errors as the format strings don't fit the type.

I think it would make more sense to just case the j here to the biggest type and avoid the if(....) cascade, e.g.

`printf("Out of range %d %lld %d %g\n", iColumn, (long long)j, row[j], elementByColumn[j]);`

**Comment by jjhforrest** [comment]
OK now? (master(

**Comment by christoph-cullmann** [comment]
Works nicely now here, thanks a lot!
