### ISSUE TITLE
Where are ClpMain0 and ClpMain1 defined?

### ISSUE THREAD

**Issue by yashpuranik** [coin-or/Clp#177]
Hi, 

I am looking at driver3.cpp in Clp examples. (https://github.com/coin-or/Clp/blob/130dd1991af524193dd4fcf572a9e370e88b6d53/examples/driver3.cpp#L29). 

I am unable to compile it, because the compiler complains about missing definitions for ClpMain0 and ClpMain1. I am also unable to find where these methods are defined in the Clp source. Can you please point me to the source for ClpMain0 and ClpMain1 and/or instructions on how to compile driver3.cpp?

**Comment by tkralphs** [comment]
They are defined around here 

https://github.com/coin-or/Clp/blob/130dd1991af524193dd4fcf572a9e370e88b6d53/src/ClpSolver.cpp#L174-L194

How are you building the example? What is the exact error?

**Comment by yashpuranik** [comment]
Ah sorry. I had a mistake in my compile scripts. Thank you and apologies for the false alarm!
