### ISSUE TITLE
Segmentation fault when solving problem with only column bounds

### ISSUE THREAD

**Issue by hongkai-dai** [coin-or/Clp#178]
I created a simple linear program problem with no rows, but only column bounds (bounds on variables). When I try to solve the program I receive segfault. Here is my code
```cc
#include "ClpSimplex.hpp"

int main() {
  ClpSimplex model;
  model.resize(0, 2);
  model.setObjectiveCoefficient(0, 1);
  model.setObjectiveCoefficient(1, -2);
  model.setColumnLower(0, 0);
  model.setColumnUpper(0, 2);
  model.setColumnLower(1, -1);
  model.setColumnUpper(1, 4);
  model.primal();
  return 0;
}
```

However if I add one row, then the program runs fine
```cc
#include "ClpSimplex.hpp"

int main() {
  ClpSimplex model;
  model.resize(0, 2);
  model.setObjectiveCoefficient(0, 1);
  model.setObjectiveCoefficient(1, -2);
  model.setColumnLower(0, 0);
  model.setColumnUpper(0, 2);
  model.setColumnLower(1, -1);
  model.setColumnUpper(1, 4);
  int row_index[] = {0, 1};
  double row_val[] = {1., 3.};
  model.addRow(2, row_index, row_val, 2., 15.);
  model.primal();
  return 0;
}
```
What is the right way to solve a linear programming problem with no rows?

**Comment by jjhforrest** [comment]
I have modified model.resize in master to better cope with a null 
matrix.  However I would suggest you use -
      double obj[]={1,-2};
      double lo[]={0,-1};
      double up[]={2,4};
      model.loadProblem(2,0,NULL,NULL,NULL,lo,up,obj,NULL,NULL);

John Forrest

**Comment by hongkai-dai** [comment]
Thanks a lot John! Using loadProblem solves the segfault!

Just curious, is "loadProblem" always preferable to `addRows`? The documentation says "loadProblem" is used after presolve, does that mean in normal case we should still use "addRows" which would incur presolve?

**Comment by jjhforrest** [comment]
I would always use loadProblem.  It is most efficient if all data is 
passed in at one go as then all arrays are setup once with correct size.

If it is easier to build model by rows, I would still use loadProblem 
with zero rows and then addRows.

**Comment by hongkai-dai** [comment]
Thanks John. I changed to use `loadProblem` in our code, it works nicely.
