### ISSUE TITLE
OsiClpSolverInterface::modelCut() is not threadsafe

### ISSUE THREAD

**Issue by tosttost** [coin-or/Clp#191]
In line 3262
```
static int debugMode = 0;
```
this global variable is then modified in line 3443. It is unclear to me when/whether this line is executed. If it is and another thread B is running modelCut it is definitely possible that debugModel was not initialized in line 3296, thread A sets debugMode to a value != 0 and thread B calls functions with an uninitialized this pointer (e.g. line 3454) causing undefined behaviour or a segmentation fault.

OsiClpSolverInterface::modelCut is used by Cbc.

**Comment by jjhforrest** [comment]
As the name suggests, this is only used for debugging - which would be 
done without threads - normally in a debugger when it would be set by 
debugger.

**Comment by tosttost** [comment]
>this is only used for debugging

I do not claim anything else. But I'm pretty sure the current implementation is not thread safe no matter if you are debugging or not.

debugMode = 0 does skip all the 'if' that modify 'debugModel'. Nevertheless debugMode is modified if modelPtr_->numberColumns_ < 0 no matter what value it had before or if we are running a debug or a release build. After that happend, the 'if' are no longer skipped.

 So unless
* modelCut() is only called in debug builds - seems unlikely to me
* or 'modelPtr_->numberColumns_ < 0' never happens in release builds

the current implementation is not thread safe in release builds, although the bug will be quite difficult to trigger.

**Comment by jjhforrest** [comment]
On 14/05/2021 10:41, tosttost wrote:

> So unless
> 
>   * modelCut() is only called in debug builds - seems unlikely to me
>   * or 'modelPtr_->numberColumns_ < 0' never happens in release builds

I think I can guarantee that modelPtr_->numberColumns() will always be 
positive.  I don't wish to lose some of that debugging code, but I will 
take out the lines

         if (numberColumns < 0)
           debugMode = -numberColumns;

John Forrest

**Comment by tosttost** [comment]
Sounds like a reasonable fix.

**Comment by tkralphs** [comment]
Just to follow up, I don't think this ever happened, right?

**Comment by tkralphs** [comment]
Oops, sorry, looks like it was done in `refactor` (5b6a9a6d82ab04dc428802adfa808612dab9ff73), which is the right place for it. I'm going to close this for now, feel free to reopen if needed.
