### ISSUE TITLE
ClpSimplex print out 

### ISSUE THREAD

**Issue by hongkai-dai** [coin-or/Clp#194]
When I use ClpSimplex class, I don't see how to set the print level. In `ClpSimplex.hpp`, I still see the documentation https://github.com/coin-or/Clp/blob/8bd93963e05771a0930c6945361dcec7d5d2b823/src/ClpSimplex.hpp#L690-L697, but there is not function there. What would be the right approach to set the print level?

**Comment by jwnimmer-tri** [comment]
Call the base class `ClpModel::setLogLevel(int)`:

https://github.com/coin-or/Clp/blob/1f0d405d632f2b1453cf5ceb4d76bbfc74c20c61/src/ClpModel.hpp#L977-L988
