### ISSUE TITLE
Incorrect solution to quadratic programme

### ISSUE THREAD

**Issue by svigerske** [coin-or/Clp#23]
Issue created by migration from Trac.

Original creator: ruminator

Original creation time: 2008-09-11 06:02:57

Assignee: somebody

Version: 

The attached MPS file contains a small problem that has the ability to confuse CLP, whereas I would expect the solution to be around 1.713e15 I have observed values in the range of 2.484e15 without presolve and 5.076e15 with. Barrier will yield results of the order of 10^23.

**Comment by svigerske** [comment]
Attachment [degenerate.mps](https://www.coin-or.org/issue-attachments/Clp/ticket23/degenerate.mps) by ruminator created at 2008-09-11 06:03:51

MPS file describing the programme

**Comment by svigerske** [comment]
Comment by ruminator created at 2008-09-11 06:06:37

Might also add that the objective is positive semidefinite

**Comment by svigerske** [comment]
Comment by @jjhforrest created at 2009-07-07 20:01:35

Matrix should only have one copy of off diagonal elements.  Still gives problems but I can get 1.71323e15

**Comment by svigerske** [comment]
Comment by @jjhforrest created at 2009-07-07 20:01:35

Changing assignee from somebody to @jjhforrest.

**Comment by svigerske** [comment]
Comment by @jjhforrest created at 2009-07-07 20:01:35

Changing status from new to assigned.

**Comment by svigerske** [comment]
@jjhforrest so you this can be closed?

**Comment by jjhforrest** [comment]
Barrier looks a bit of a mess.  Simplex is consistent when I scale it in different ways.  The difference with and without  presolve is still there (smaller).  May look at that so leave this open

**Comment by jjhforrest** [comment]
Finger trouble

**Comment by jjhforrest** [comment]
Looks as if objective is not convex - so obviously we can get local minima
