### ISSUE TITLE
1.17.7 Msvc release builds contain linux libraries

### ISSUE THREAD

**Issue by victorbai** [coin-or/Clp#238]
I just noticed that the latest 1.17.7 building binaries contains wrong library files.  The msvc builds are in fact linux libaraies instead of windows library. 

![image](https://user-images.githubusercontent.com/9535610/180341360-0f70b16f-b9d9-4d0d-8bf7-2ec352494692.png)

[Clp-releases.1.17.7-w64-msvc15-md.zip](https://github.com/coin-or/Clp/releases/download/releases%2F1.17.7/Clp-releases.1.17.7-w64-msvc15-md.zip)

Jan 12, 2022
[Clp-releases.1.17.7-w64-msvc15-mdd.zip](https://github.com/coin-or/Clp/releases/download/releases%2F1.17.7/Clp-releases.1.17.7-w64-msvc15-mdd.zip)

Jan 12, 2022
[Clp-releases.1.17.7-w64-msvc16-md.zip](https://github.com/coin-or/Clp/releases/download/releases%2F1.17.7/Clp-releases.1.17.7-w64-msvc16-md.zip)

Jan 12, 2022
[Clp-releases.1.17.7-w64-msvc16-mdd.zip](https://github.com/coin-or/Clp/releases/download/releases%2F1.17.7/Clp-releases.1.17.7-w64-msvc16-mdd.zip)

Jan 12, 2022

**Comment by tkralphs** [comment]
Yes, sorry, this is because of a bug in the CI and I haven't made a new release yet to correct it. If you get the binaries for the latest release of [Cbc](https://github.com/coin-or/Cbc), they include Clp. Please also note coin-or/Cbc#522, however.

**Comment by victorbai** [comment]
@tkralphs Thanks for the responsive reply. It makes sense. Actually, I downloaded an older build, and just came across the same linking issue you mentioned.  Your notes help a lot. I will build myself instead.

**Comment by tkralphs** [comment]
It's been a while, but just in case, I wanted to note that the newest releases now correctly have MSVC libraries, but coin-or/Cbc/#522 is still an issue. That should also be fixed shortly.
