### ISSUE TITLE
Is there a way to gracefully terminate a long running `ClpSimplex::primal` or `ClpSimplex::dual`?

### ISSUE THREAD

**Issue by sebrockm** [coin-or/Clp#256]
In my C++ project I'm solving linear programs using `ClpSimplex::primal` and `ClpSimplex::dual`. Unfortunately, for some instances this takes very long and I cannot find a way to terminate them. I would imagine something like a timeout parameter or stop token. Have I missed anything in the docs?

My current workaround is to spawn them on a different thread and simply detach from that if the solution is not available after some time. This at least allows my program flow to continue, but still one CPU core is busy and lots of memory is being consumed for an uncertain amount of time.

**Comment by Iain-R** [comment]
Hi, You might have some luck with either setMaximumSeconds() or setMaximumIterations().
Documentation on Doxygen  can be found [here](https://coin-or.github.io/Clp/Doxygen/classClpModel.html#a752ecb8ee0f2e05ed3634bfb02df0ff0)

**Comment by sebrockm** [comment]
Thanks for the quick answer! Yes, that looks rather obvious. No idea how I missed that...

I will run some tests with it and, if everything works as expected, close this issue. Thanks again!

**Comment by sebrockm** [comment]
Yep, it works, exactly what I was looking for, thanks @Iain-R!

BTW, the reason why I didn't find it myself was that I only looked into `ClpSimplex`'s [documentation](https://coin-or.github.io/Clp/Doxygen/classClpSimplex.html) where only inherited member variables show up, but no inherited methods. Is that on purpose?

Still, my bad that I didn't look at the base class.
