### ISSUE TITLE
What is a singleton column exactly?

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [coin-or/Clp#272]
I am looking at some stats for an LP problem from the cli and I see the mention `singleton`. My guess is that these are columns with no coefficients in the constraints matrix, am I right?

Here an example

```
Clp:stat    
Statistics for unpresolved model


Problem has 192391 rows, 550881 columns (550881 with objective) and 5831017 elements
There are 96290 singletons with objective 
```

**Comment by jjhforrest** [comment]
No - just one coefficient.  If it had zero objective, then it could be removed and the lower and upper bounds on constraint modified.  If there is an objective for that column it is more complicated but there are several ways in which the column could be removed by presolve e.g. by subtracting out an equality row from objective.

**Comment by andrea-cassioli-maersk** [comment]
Thanks @jjhforrest for the clarification.
