### ISSUE TITLE
Clp writebasis potential bug

### ISSUE THREAD

**Issue by a-zakir** [coin-or/Clp#277]
Hello,
ClpSimplex::writeBasis is a call to ClpSimplexOther::writeBasis which declares an array of char with the wrong size 20 . This variable is sent to another function that expects a larger array (CoinConvertDouble (int section, int formatType, double value, **char outputValue[24]*)). If format=1 then CoinConvertDouble attempt to **memset** 24 bytes of variable **number** which has only 20 then the behavior of [memset](https://en.cppreference.com/w/cpp/string/byte/memset) is undefined.

regards

**Comment by jjhforrest** [comment]
Thanks.  Doesn't look like it can cause problems - so only corrected in master.

**Comment by a-zakir** [comment]
Thank you
