### ISSUE TITLE
Failed to building by "make"

### ISSUE THREAD

**Issue by waldstein1983** [coin-or/Clp#3]
Hi,
I clone one copy by git and try to build it.
But it fails at "make" step, with an error relating to CoinFactorization (The detail is missing....)
Then, I use “svn co https://projects.coin-or.org/svn/Clp/trunk Coin-Clp” to download another copy and it builds successfully.
Is there any difference between those 2 copies? If there is, I suggest fixing this gap :-)
Thx

**Comment by tkralphs** [comment]
This is explained in detail here:

https://github.com/coin-or/Cbc/issues/1

The instructions for building [Cbc](https://projects.coin-or.org/Cbc) [here](https://projects.coin-or.org/Cbc#DownloadandInstall) will also work for Clp (substituting appropriate URLs). I just haven't found the time to propagate this information to other projects. Hope this helps!

**Comment by waldstein1983** [comment]
Thanks Ted,
I find that CoinUtils is not there :-)

2017-06-06 11:58 GMT+08:00 Ted Ralphs <notifications@github.com>:
