### ISSUE TITLE
Add a ClpMain0 class to call main programmatically

### ISSUE THREAD

**Issue by svigerske** [coin-or/Clp#64]
Issue created by migration from Trac.

Original creator: @ycollet

Original creation time: 2014-03-04 12:00:42

Assignee: somebody

Version: 

A new ClpMain0 class which containts de code from main should be added (like what has been done in Cbc) to be able to call the main logic and options like with the clp executable.

**Comment by svigerske** [comment]
A ClpMain0() function seems to exist in ClpMain.cpp. All that would be to do is to expose this function through some header file and library (instead of executable).

**Comment by jjhforrest** [comment]
driver3.cpp in Clp/examples does this

**Comment by svigerske** [comment]
Ah, I was wrong. ClpMain0() and ClpMain1() are implemented in ClpSolver.cpp, which is part of libClpSolver. Would be nice to have a ClpSolver.hpp header file that takes care of the function declarations.
