### ISSUE TITLE
Infeasibility Ray not found

### ISSUE THREAD

**Issue by svigerske** [coin-or/Clp#79]
Issue created by migration from Trac.

Original creator: blegat

Original creation time: 2016-12-31 16:38:51

Assignee: somebody

Version: 

Dear Clp maintainers,

I am using Clp v1.16.1 through the Julia wrapper for doing SDDP (https://github.com/blegat/StochasticDualDynamicProgramming.jl).
For that algorithm, when a problem is infeasible, it important to retrieve an infeasibility ray.
When I use Clp, it often happens that no infeasibility ray are returned by Clp.

I have tried to create the simplest possible example of problem for which Clp detects the infeasibility of the problem but does not find infeasibility ray and I have attached it to this ticket. I hope that this example will help you detect the issue in Clp and fix it !

The example is the following:
Minimize 0
Subject To
 x0 + x3 + x6 == 2
 x1 + x4 + x7 == 2
 x2 + x5 + x8 == 2
 x0 + x1 + x2 <= 1
 x3 + x4 + x5 <= 1
 x6 + x7 + x8 <= 1
 xi >= 0
Bounds
 xi free
End
As you can see, there are 6 + 9 constraints but no bounds on the variables. If the last 9 constraints are used as bounds or are removed, the infeasibility ray is found by Clp.
The Infeasibility Ray is [1,1,1,-1,-1,-1,0,0,0,0,0,0,0,0,0]. Indeed, the sum of the 3 first constraints give "sum xi = 6" while the sum of the 3 following constraints give "sum xi <= 3".

Thanks in advance for your time !

**Comment by svigerske** [comment]
Attachment [clpfail.mps](https://www.coin-or.org/issue-attachments/Clp/ticket79/clpfail.mps) by blegat created at 2016-12-31 16:40:34

Example in MPS format

**Comment by svigerske** [comment]
Attachment [clpfail.lp](https://www.coin-or.org/issue-attachments/Clp/ticket79/clpfail.lp) by blegat created at 2016-12-31 16:40:57

Example in LP format

**Comment by svigerske** [comment]
Comment by blegat created at 2016-12-31 16:46:24

The example is not formatted properly in the previous message and I can't find how to modify it so I have reformatted it below:
```
Minimize 0

Subject To

x0 + x3 + x6 == 2
x1 + x4 + x7 == 2
x2 + x5 + x8 == 2
x0 + x1 + x2 <= 1
x3 + x4 + x5 <= 1
x6 + x7 + x8 <= 1
xi >= 0

Bounds

xi free

End
```

**Comment by svigerske** [comment]
One would probably need a Julia file to reproduce this issue and then @mlubin or @joehuchette should talk to @jjhforrest whether some flags need to be set in the Julia/Clp wrapper to convince Clp to look carefully for a ray. E.g., the SCIP/Clp interface seems to set Clp special option 2097152, which may be related.

**Comment by mlubin** [comment]
CC @blegat

**Comment by uhrm** [comment]
I'd like to pick up on this problem, since I think I'm running into a similar problem.

Here are two C programs that reproduce the problem with Clp version 1.17.9:

```C
#include <assert.h>
#include <math.h>
#include <stdbool.h>
#include <stdio.h>

#include <Clp_C_Interface.h>

#define INF INFINITY

//   Minimize:
// 
//     0
// 
//   Subject to:
// 
//     x0 +           x3 +           x6           == 2
//          x1 +           x4 +           x7      == 2
//               x2 +           x5 +           x8 == 2
//     x0 + x1 + x2                               <= 1
//                    x3 + x4 + x5                <= 1
//                                   x6 + x7 + x8 <= 1
//     x0                                         >= 0
//          x1                                    >= 0
//               x2                               >= 0
//                    x3                          >= 0
//                         x4                     >= 0
//                              x5                >= 0
//                                   x6           >= 0
//                                        x7      >= 0
//                                             x8 >= 0
// 
//   With:
// 
//     x0, ..., x8 free.

int main(int argc, char *argv[]) {
    Clp_Simplex* mod = Clp_newModel();
    Clp_setLogLevel(mod, 2);

    int    Aj[10] = {  0,             3,             6,             9,            12,            15,            18,            21,            24,            27 };
    int    Ai[27] = {  0,   3,   6,   1,   3,   7,   2,   3,   8,   0,   4,   9,   1,   4,  10,   2,   4,  11,   0,   5,  12,   1,   5,  13,   2,   5,  14 };
    double Ax[27] = { 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 };
    double lb[9]  = {-INF, -INF, -INF, -INF, -INF, -INF, -INF, -INF, -INF };
    double ub[9]  = { INF,  INF,  INF,  INF,  INF,  INF,  INF,  INF,  INF };
    double obj[9] = { 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0 };
    double bl[15] = { 2.0,  2.0,  2.0, -INF, -INF, -INF,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0 };
    double bu[15] = { 2.0,  2.0,  2.0,  1.0,  1.0,  1.0,  INF,  INF,  INF,  INF,  INF,  INF,  INF,  INF,  INF };
    Clp_loadProblem(mod, 9, 15, Aj, Ai, Ax, lb, ub, obj, bl, bu);


    Clp_initialSolve(mod);
    assert(Clp_status(mod) == 1/*primal infeasible*/);

    double* infray = Clp_infeasibilityRay(mod);
    assert(infray != NULL);

    Clp_freeRay(mod, infray);
    Clp_deleteModel(mod);
}
```
and
```C
#include <assert.h>
#include <math.h>
#include <stdbool.h>
#include <stdio.h>

#include <Clp_C_Interface.h>

#define INF INFINITY

//   Minimize:
// 
//     0
// 
//   Subject to:
// 
//     x0 +           x3 +           x6           == 2
//          x1 +           x4 +           x7      == 2
//               x2 +           x5 +           x8 == 2
//     x0 + x1 + x2                               <= 1
//                    x3 + x4 + x5                <= 1
//                                   x6 + x7 + x8 <= 1
// 
//   With:
// 
//     x0, ..., x8 >= 0.

int main(int argc, char *argv[]) {
    Clp_Simplex* mod = Clp_newModel();
    Clp_setLogLevel(mod, 2);

    int    Aj[10] = {  0,         2,        4,        6,        8,       10,       12,       14,       16,        18 };
    int    Ai[18] = {  0,    3,   1,   3,   2,   3,   0,   4,   1,   4,   2,   4,   0,   5,   1,   5,   2,   5 };
    double Ax[18] = { 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 };
    double lb[9]  = { 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0 };
    double ub[9]  = { INF,  INF,  INF,  INF,  INF,  INF,  INF,  INF,  INF };
    double obj[9] = { 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0 };
    double bl[15] = { 2.0,  2.0,  2.0, -INF, -INF, -INF };
    double bu[15] = { 2.0,  2.0,  2.0,  1.0,  1.0,  1.0 };
    Clp_loadProblem(mod, 9, 6, Aj, Ai, Ax, lb, ub, obj, bl, bu);


    Clp_initialSolve(mod);
    assert(Clp_status(mod) == 1/*primal infeasible*/);

    double* infray = Clp_infeasibilityRay(mod);
    assert(infray != NULL);

    Clp_freeRay(mod, infray);
    Clp_deleteModel(mod);
}
```
The first variant with free variables fails to find the infeasibility ray. The second variant with variable bounds succeeds.

**Comment by jjhforrest** [comment]
The problem seems to be that initialSolve does a presolve.  When it is infeasible and the postsolve is simple, the ray is kept.  In the first variant you get
Coin0505I Presolved problem not optimal, resolve after postsolve
Coin0511I After Postsolve, objective 0, infeasibilities - dual 0 (0), primal 3.899998 (2)

and the ray vanishes.  I will look further - for the moment you could switch off presolve i.e. replace initialSolve with

    Clp_Solve *options = ClpSolve_new();
    // 1 corresponds to presolveOff (which is not intuitive)
    ClpSolve_setPresolveType(options,1,0);
    Clp_initialSolveWithOptions(mod,options);
    ClpSolve_delete(options);

**Comment by jjhforrest** [comment]
It was a bug.  initialSolve is meant to make sure the original problem is in a good state after postsolve.  The code at line 3821 of ClpSolve.cpp was       if (!finalStatus || finalStatus == 2 || 
then make sure.  status 0
of 0 is optimal and 2 is unbounded.  So it should have been
      if ((finalStatus>=0 && finalStatus <= 2)...

to include 1 which is primal infeasible.

Corrected in master and stable
