### ISSUE TITLE
Infeasible solution returned when problem is unbounded

### ISSUE THREAD

**Issue by svigerske** [coin-or/Clp#80]
Issue created by migration from Trac.

Original creator: blegat

Original creation time: 2017-01-23 15:49:27

Assignee: somebody

Version: 

Dear Clp maintainers,

When trying to solve the following problem

```
Maximize x1

Subject To

x1 >= 1

Bounds

x1 free
x2 <= -1

End
```

Clp detects unboundedness and reports a correct unbounded ray but returns an infeasible solution (i.e. `[0, 0]`).

Can we expect Clp to return a feasible solution when the problem is unbounded ? We are currently wondering whether this is a reasonable expectation for LP solver [here](https://github.com/JuliaOpt/MathProgBase.jl/pull/144).

**Comment by svigerske** [comment]
Comment by blegat created at 2017-04-07 11:35:00

I asked the same question for Gurobi (here: https://groups.google.com/forum/#!topic/gurobi/cKZY6huEBZo) and they replied that the solver stops as soon as it finds an unbounded ray and therefore has no guarantee on the feasibility of the problem. This is also explained here: https://www.gurobi.com/documentation/7.0/refman/optimization_status_codes.html
Therefore, to obtain a feasible solution, one needs to set the objective to 0 and reoptimize.
Is it the same for Clp ?

**Comment by svigerske** [comment]
@jjhforrest Does Clp do anything to ensure feasible solutions if unbounded?

**Comment by jjhforrest** [comment]
If using primal will return feasible solution.  I don't think dual can easily do that.  If user is coding a driver then trivial to switch to primal if unbounded.
