### ISSUE TITLE
Index range error (underrun) in ClpPrimalColumnSteepest::partialPricing (tested with Clp-1.16.11)

### ISSUE THREAD

**Issue by svigerske** [coin-or/Clp#86]
Issue created by migration from Trac.

Original creator: jhusr

Original creation time: 2019-02-19 11:30:48

Assignee: somebody

Version: 

In ClpPrimalColumnSteepest::partialPricing we find following declarations:

double * duals = model_->dualRowSolution(); // array size of ClpModel::dual_ is ClpModel::numberRows_
double * duals2 = duals - numberColumns.

If ClpModel::dual_ is accessed using duals2[iSequence] resp. duals[bestSequence-numberColumns]
an index underrun error occurs when the indices iSequence resp. bestSequence have a 
value < numberColumns. 
This can be verified using the macro _ASSERT_DUAL_ROW_SOL_PTR_(x) in the modified source code attached.

Use Visual Studio, debug configuration:
The underrun checks have been implemented in ClpPrimalColumnSteepest.cpp, look for "DUAL_ROW_SOLUTION_UNDERRUN_CHECK".

Test condition:
Force switchType = 5 manually in ClpPrimalColumnSteepest::pivotColumn (done in modified source, which is attached).

Try e.g. P0033, or netlib example PEROLD.

**Comment by svigerske** [comment]
Comment by jhusr created at 2019-02-19 11:44:15

Attaching the modified source file resulted in "TRAC IndexError: pop from empty list".
I try to send the modification by e-mail.

**Comment by svigerske** [comment]
Please try attaching a patch here.

**Comment by jjhforrest** [comment]
Coding is such that we are doing rows - so sequence number >= numberColumns.  Added assert to keep people happy. BTW mode 5 is very slow.
