### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by gamaanderson** [coin-or/Clp#87]
Hello

I'm using cylp to solve a big and sometimes infeasible problem and I'm getting the following error:

```
Coin0507I Presolve determined that the problem was infeasible with tolerance of 1e-08
Clp3003W Analysis indicates model infeasible or unbounded
python: ClpSimplex.cpp:3739: bool ClpSimplex::createRim(int, bool, int): Assertion `fabs(obj[i]) < 1.0e25' failed.
```

This error is intermittent, meaning that I can run again the exact same code/problem and it will run with no error. I would like to get some insight in what is this assertion and what could be causing it. I don't need a full debug, just some insight

System: Ubuntu 14.04
CyLP 0.7.2

**Comment by svigerske** [comment]
This looks like a hard check in Clp that the objective coefficients (in absolute value) do not get too huge.
