### ISSUE TITLE
Can't change Clp algorithm

### ISSUE THREAD

**Issue by svigerske** [coin-or/Clp#95]
Issue created by migration from Trac.

Original creator: Rusker

Original creation time: 2015-08-26 17:47:28

Assignee: @mjsaltzman

Version: 0.104

Hi, I hope this is the correct way to present my problem.

In the past I've been able to change the algorithm used by Clp in initialSolve in the following way:

```
OsiClpSolverInterface *osiSlvr = new OsiClpSolverInterface();

ClpSolve clpSolve;

clpSolve.setSolveType(ClpSolve::useBarrier);

osiSlvr->setSolveOptions(clpSolve);

osiSlvr->initialSolve();

```

Now I'm working on a more complicated program that has to solve a problem more than one time, so I'm using an initialSolve followed by (a certain amount of) resolve(). If I use the same code as above, I don't seem to be able to switch between Primal, Dual and Barrier. I can use the hints to ask for Primal or Dual in solve/resolve, but I'm not sure it's the same thing.

Is there something wrong in the code above? Or is there something different I have to do to change the algorithm used in resolve? Any help is appreciated.

**Comment by jjhforrest** [comment]
hints for dual/primal will work in resolve.  Unlikely to want barrier for a resolve but then you could use getModelPtr()->barrier() (You could also use getModelPtr() for more control of primal/dual)
