### ISSUE TITLE
Floating point exception produced on tiny input

### ISSUE THREAD

**Issue by constantinosTsirogiannis** [coin-or/Clp#96]
Greetings,

Before starting with this bug report, I would like to say many thanks for developing and maintaining CLP. I am currently using this library on complex combinatorial problems that arise in microchip design, and I am more than satisfied with its efficiency and reliability.

Unfortunately, recently I came across a dataset that causes CLP to produce a floating point exception. This problem appears on the following instance with a 3X3 matrix (the corresponding C++ code is attached here on a separate file):  

Ax <= b

where x={x_0,x_1,_x2}, and A and b are described by the following constraints:

-0.165261 <=      x_0      -x_1       <= 0.006982
-infinity <=     -x_0 +     x_1 + x_2 <= 0.114778
-infinity <= -2.0*x_0 + 2.0*x_1 + x_2 <= 0.229850

The variables are bounded by the following values:

-0.285000 <= x_0 <= 0.090530
-0.285000 <= x_1 <= 0.083548
-infinity <= x_2 <= 0.0

The objective function is simply c(x)= x_2 .

This problem instance is feasible with optimal value c(x)=0.0 and has an infinite set of optimal solutions e.g. just pick any allowed values for x_0 and x_1 such that x_0=x_1, and set x_2=0.

The floating point exeption appears during the execution of function:
remove_dual_action::presolve(CoinPresolveMatrix*, CoinPresolveAction const*) ()

The CLP version that I used was 1.16.10 and it was compiled on a linux server with gcc version 6.2.0 .

I am really puzzled as to why this exception happens. Could it be that I am populating the CLP structures in a wrong manner? If yes, could you indicate a better way to do this? I am surprised though that this could be the reason since I have been able to solve much more complicated instances using the same way of populating the clp matrix and simplex solver. 

On the other hand, if this is a known CLP bug, could you indicate some rule of thumb for avoiding such crashes? Is there a degeneracy in the way that the above input is defined? For instance, I noticed that if I substitute the last constraint in A with the following constraint and introduce a fourth variable x_3 then I get CLP running correctly:

-infinity <= -x_0 + x_1 + x_3 <= 0.115071 ,  and with c(x) now set to c(x)= x_2 + x_3

I will be really grateful if you could provide feedback on this issue.

Best regards,

Constantinos

[floating_point_exception_example.txt](https://github.com/coin-or/Clp/files/2977620/floating_point_exception_example.txt)

**Comment by jjhforrest** [comment]
I am unable to reproduce error.

Does it happen in debug mode?  Can you give any more details on 
compiling code (I initially got errors as my compiler wanted std::cout).

John Forrest

**Comment by constantinosTsirogiannis** [comment]
Thanks for the quick reply! So, if I understand correctly, you managed to run a program which uses the attached code and in this program the simplex solver executed correctly, without reproducing the error? If that is the case, then probably there is something wrong in my build settings, or the platform that I use. 

I am not running in debug mode. As far as I know, the only floating-point related flags that are the standard flags for 64bit code.

**Comment by svigerske** [comment]
I also cannot reproduce this with current Clp/master (gcc 8.2):
```
$ g++ floating_point_exception_example.cpp -Iinclude/coin `cat share/coin/doc/Cbc/cbc_addlibs.txt` -g -O0 && ./a.out 
 Matrix: 
1 0
-1 1
-1 0
1 1
1 2
-2 0
2 1
1 2
 Row start: 
0
2
5
8
 Boundaries columns: 
-0.285 0.09053
-0.285 0.083548
-inf 0
 Boundaries rows: 
-0.165261 0.006982
-inf 0.114778
-inf 0.22985
 Objective function: 
0
0
1
Coin0506I Presolve 3 (0) rows, 3 (0) columns and 8 (0) elements
Clp0000I Optimal - objective value 0
Clp0032I Optimal objective 0 - 0 iterations time 0.002
Clp0000I Optimal - objective value 0
```
As John suggested, please give more details like used compiler flags. Also try using Clp/master (or trunk) or a 1.17 release.

**Comment by constantinosTsirogiannis** [comment]
Thanks for looking at this. I agree that it must be something with the compilation flags. Therefore, I will just try to examine this myself in my own build and figure out what causes it. 

A last request: if it is not too much of work for you, could you run this example specifically on CLP version 1.16.10 (and if possible with gcc version 6.2.0 and with no additional flags) to rule out totally that it is not an issue in the specific version?

Thanks for all the help and feel free to close this issue afterwards.

**Comment by svigerske** [comment]
I downloaded [Clp 1.16.10](https://www.coin-or.org/download/source/Clp/Clp-1.16.10.tgz) and did a configure && make (thus not debug) and got the same as before. Still gcc 8.2 though. I'm not going to install an old compiler :).

**Comment by constantinosTsirogiannis** [comment]
Ok, thanks!
